### ISSUE TITLE
Replace kotlinx-cli with clikt

### ISSUE THREAD

**Issue by platan** [platan/tests-execution-chart#73]
According to https://github.com/Kotlin/kotlinx-cli:
> This library is obsolete
It is effectively unmaintained. Please consider using other libraries.

Let's replace it with other library. https://github.com/ajalt/clikt seems to be the most popular one. 

https://github.com/platan/tests-execution-chart/blob/34a6d657e4e69a744065b9fb4706bb536ffecea1/src/functionalTest/kotlin/io/github/platan/tests_execution_chart/JsonToHtmlReportApp.kt uses kotlinx-cli. 

`JsonToHtmlReportApp is used by `createRegressionHtmlReport` task. The task is defined in https://github.com/platan/tests-execution-chart/blob/main/build.gradle.kts. Regression tests [use](https://github.com/platan/tests-execution-chart/blob/main/.github/workflows/ci.yml) `createRegressionHtmlReport`. 

If required, `JsonToHtmlReportApp` cli parameters can be changed.

**Comment by KKolej** [comment]
I will check it
