### ISSUE TITLE
Replace groovy.json.JsonOutput with kotlinx.serialization.json in JsonReporter

### ISSUE THREAD

**Issue by platan** [platan/tests-execution-chart#74]
tests-execution-chart-commons module already has kotlinx-serialization-json as a dependency. But we use `groovy.json` package in `JsonReporter`. Let's replace `groovy.json` with `kotlinx.serialization.json` and reduce dependency to `groovy`. 

TODO:
- replace `groovy.json.JsonOutput` with `kotlinx.serialization.json` (https://github.com/Kotlin/kotlinx.serialization) in JsonReporter
- remove dependency to `implementation(localGroovy())` in `tests-execution-chart-commons/build.gradle.kts`
- add tests for `JsonReporter` :-)

**Comment by jglaszka** [comment]
I can take this task
