### ISSUE TITLE
Add unit tests for HtmlGanttDiagramReporter 

### ISSUE THREAD

**Issue by jglaszka** [platan/tests-execution-chart#78]
Class [HtmlGanttDiagramReporter](https://github.com/platan/tests-execution-chart/blob/d3470e0ffdc336e53a99740bb315d2ccefdf11a0/tests-execution-chart-commons/src/main/kotlin/io/github/platan/tests_execution_chart/reporters/html/HtmlGanttDiagramReporter.kt#L19) generates reports in form of visual HTML chart and saves it to the file. Unfortunately, it does not have unit tests. 
Todo:
- implement test cases for HtmlGanttDiagramReporter in Groovy (spock)

**Comment by platan** [comment]
I've slightly refactored reporters and added missing tests.
