### ISSUE TITLE
Add unit tests for MermaidTestsReporter

### ISSUE THREAD

**Issue by jglaszka** [platan/tests-execution-chart#79]
Class [MermaidTestsReporter](https://github.com/platan/tests-execution-chart/blob/cb0c65780533dd16e11b015b5a9c123576ed61ec/tests-execution-chart-commons/src/main/kotlin/io/github/platan/tests_execution_chart/reporters/mermaid/MermaidTestsReporter.kt#L8) generates reports in form of Mermaid diagrams and saves it to the file. Unfortunately, it does not have unit tests.

Todo:
- implement test cases for MermaidTestsReporter in Groovy (spock)

**Comment by platan** [comment]
I've slightly refactored reporters and added missing tests.
